apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer-app
  name: consumer-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - image: consumer-app:1.1.0
        imagePullPolicy: Never
        name: consumer-app
